export const ViewportTypes = {
	MOBILE: 'MOBILE',
	TABLET: 'TABLET',
	DESKTOP: 'DESKTOP'
};

export const ActionTypes = {
	REQUEST_PROJECTS: 'REQUEST_PROJECTS',
	RECEIVE_PROJECTS_SUCCESS: 'RECEIVE_PROJECTS_SUCCESS',
	RECEIVE_PROJECTS_FAILURE: 'RECEIVE_PROJECTS_FAILURE',
	SELECT_PROJECT: 'SELECT_PROJECT',
	SELECT_VIEWPORT: 'SELECT_VIEWPORT'
};